### ISSUE TITLE
Why are float64 parsed, but only exposed as float32 ?

### ISSUE THREAD

**Issue by Keenuts** [udhos/gwob#2]
The parsing is made using float64.
But once inserted in public structures, it's exposed as float32, why ?

Shouldn't we switch all the exposed float to 64 bit long floats ?

**Comment by udhos** [comment]
Well, when I put the package in place, I actually needed the vertex data as float32 for WebGL.
That's why it the struct Obj has the member Coord as []float32.
I suppose a more complete approach would offer an API to allow the user to specify the desired float type as either float32 or float64.
