### ISSUE TITLE
Support obj writer

### ISSUE THREAD

**Issue by mikialex** [udhos/gwob#3]
Wish to have a simple writer support for convenience :)

**Comment by udhos** [comment]
Yes, I think it would be cool, however I can't figure out the use case.
I mean, if 'gwob' has just parsed the OBJ file for you, why would you want to write it back as an OBJ file?
Or am I misinterpreting the request?

**Comment by mikialex** [comment]
I'm using gwob for data processing. Read obj file and some other info, and modify parsed geometry, and write to a new obj file.

**Comment by udhos** [comment]
@mikialex I have added experimental support for exporting OBJ to file. See methods Obj.ToFile() and Obj.ToWriter(). Can you check that they meet your need?

**Comment by mikialex** [comment]
I wrote some simple code try to do write obj before, and  I cant get right result for some case. By using your supported method, some bad case fixed, and still some case not worked. So, seems maybe other part is broken....     thanks for your support really!
